# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceRecognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66\x61\x63\x65Recognition.proto\x12\x11numproto.protobuf\"#\n\x0frecognitionInit\x12\x10\n\x08\x63\x61meraIP\x18\x01 \x01(\t\"\'\n\x16\x46\x61\x63\x65RecognitionProcess\x12\r\n\x05image\x18\x01 \x01(\x0c\" \n\x0e\x46\x61\x63\x65IDResponse\x12\x0e\n\x06\x66\x61\x63\x65ID\x18\x01 \x01(\x05\"&\n\x15\x46\x61\x63\x65\x44\x65tectionResponse\x12\r\n\x05\x66\x61\x63\x65s\x18\x01 \x01(\x0c\")\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x0e\n\x06\x66\x61\x63\x65ID\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xf3\x03\n\x0cRecognitions\x12I\n\trecognise\x12\".numproto.protobuf.recognitionInit\x1a\x18.numproto.protobuf.Empty\x12S\n\x0cprocessImage\x12).numproto.protobuf.FaceRecognitionProcess\x1a\x18.numproto.protobuf.Empty\x12\x61\n\ndetectFace\x12).numproto.protobuf.FaceRecognitionProcess\x1a(.numproto.protobuf.FaceDetectionResponse\x12Z\n\ngetFaceID1\x12).numproto.protobuf.FaceRecognitionProcess\x1a!.numproto.protobuf.FaceIDResponse\x12=\n\x07\x61\x64\x64\x46\x61\x63\x65\x12\x18.numproto.protobuf.Empty\x1a\x18.numproto.protobuf.Empty\x12\x45\n\x0ftrainRecognizer\x12\x18.numproto.protobuf.Empty\x1a\x18.numproto.protobuf.Emptyb\x06proto3')



_RECOGNITIONINIT = DESCRIPTOR.message_types_by_name['recognitionInit']
_FACERECOGNITIONPROCESS = DESCRIPTOR.message_types_by_name['FaceRecognitionProcess']
_FACEIDRESPONSE = DESCRIPTOR.message_types_by_name['FaceIDResponse']
_FACEDETECTIONRESPONSE = DESCRIPTOR.message_types_by_name['FaceDetectionResponse']
_FACERECOGNITIONRESPONSE = DESCRIPTOR.message_types_by_name['FaceRecognitionResponse']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
recognitionInit = _reflection.GeneratedProtocolMessageType('recognitionInit', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONINIT,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:numproto.protobuf.recognitionInit)
  })
_sym_db.RegisterMessage(recognitionInit)

FaceRecognitionProcess = _reflection.GeneratedProtocolMessageType('FaceRecognitionProcess', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONPROCESS,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:numproto.protobuf.FaceRecognitionProcess)
  })
_sym_db.RegisterMessage(FaceRecognitionProcess)

FaceIDResponse = _reflection.GeneratedProtocolMessageType('FaceIDResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEIDRESPONSE,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:numproto.protobuf.FaceIDResponse)
  })
_sym_db.RegisterMessage(FaceIDResponse)

FaceDetectionResponse = _reflection.GeneratedProtocolMessageType('FaceDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETECTIONRESPONSE,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:numproto.protobuf.FaceDetectionResponse)
  })
_sym_db.RegisterMessage(FaceDetectionResponse)

FaceRecognitionResponse = _reflection.GeneratedProtocolMessageType('FaceRecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONRESPONSE,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:numproto.protobuf.FaceRecognitionResponse)
  })
_sym_db.RegisterMessage(FaceRecognitionResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:numproto.protobuf.Empty)
  })
_sym_db.RegisterMessage(Empty)

_RECOGNITIONS = DESCRIPTOR.services_by_name['Recognitions']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOGNITIONINIT._serialized_start=44
  _RECOGNITIONINIT._serialized_end=79
  _FACERECOGNITIONPROCESS._serialized_start=81
  _FACERECOGNITIONPROCESS._serialized_end=120
  _FACEIDRESPONSE._serialized_start=122
  _FACEIDRESPONSE._serialized_end=154
  _FACEDETECTIONRESPONSE._serialized_start=156
  _FACEDETECTIONRESPONSE._serialized_end=194
  _FACERECOGNITIONRESPONSE._serialized_start=196
  _FACERECOGNITIONRESPONSE._serialized_end=237
  _EMPTY._serialized_start=239
  _EMPTY._serialized_end=246
  _RECOGNITIONS._serialized_start=249
  _RECOGNITIONS._serialized_end=748
# @@protoc_insertion_point(module_scope)
