# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceRecognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66\x61\x63\x65Recognition.proto\"#\n\x0frecognitionInit\x12\x10\n\x08\x63\x61meraIP\x18\x01 \x01(\t\"\'\n\x16\x46\x61\x63\x65RecognitionProcess\x12\r\n\x05image\x18\x01 \x01(\x0c\" \n\x0e\x46\x61\x63\x65IDResponse\x12\x0e\n\x06\x66\x61\x63\x65ID\x18\x01 \x01(\x05\"?\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x0e\n\x06\x66\x61\x63\x65ID\x18\x01 \x01(\x05\x12\x14\n\x0c\x63ontainsFace\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty2\xa0\x02\n\x0cRecognitions\x12%\n\trecognise\x12\x10.recognitionInit\x1a\x06.Empty\x12\x41\n\x0cprocessImage\x12\x17.FaceRecognitionProcess\x1a\x18.FaceRecognitionResponse\x12\x36\n\ngetFaceID1\x12\x17.FaceRecognitionProcess\x1a\x0f.FaceIDResponse\x12\x36\n\ngetFaceID2\x12\x17.FaceRecognitionProcess\x1a\x0f.FaceIDResponse\x12\x36\n\ngetFaceID3\x12\x17.FaceRecognitionProcess\x1a\x0f.FaceIDResponseb\x06proto3')



_RECOGNITIONINIT = DESCRIPTOR.message_types_by_name['recognitionInit']
_FACERECOGNITIONPROCESS = DESCRIPTOR.message_types_by_name['FaceRecognitionProcess']
_FACEIDRESPONSE = DESCRIPTOR.message_types_by_name['FaceIDResponse']
_FACERECOGNITIONRESPONSE = DESCRIPTOR.message_types_by_name['FaceRecognitionResponse']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
recognitionInit = _reflection.GeneratedProtocolMessageType('recognitionInit', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONINIT,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:recognitionInit)
  })
_sym_db.RegisterMessage(recognitionInit)

FaceRecognitionProcess = _reflection.GeneratedProtocolMessageType('FaceRecognitionProcess', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONPROCESS,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionProcess)
  })
_sym_db.RegisterMessage(FaceRecognitionProcess)

FaceIDResponse = _reflection.GeneratedProtocolMessageType('FaceIDResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEIDRESPONSE,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceIDResponse)
  })
_sym_db.RegisterMessage(FaceIDResponse)

FaceRecognitionResponse = _reflection.GeneratedProtocolMessageType('FaceRecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONRESPONSE,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionResponse)
  })
_sym_db.RegisterMessage(FaceRecognitionResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'faceRecognition_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_RECOGNITIONS = DESCRIPTOR.services_by_name['Recognitions']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOGNITIONINIT._serialized_start=25
  _RECOGNITIONINIT._serialized_end=60
  _FACERECOGNITIONPROCESS._serialized_start=62
  _FACERECOGNITIONPROCESS._serialized_end=101
  _FACEIDRESPONSE._serialized_start=103
  _FACEIDRESPONSE._serialized_end=135
  _FACERECOGNITIONRESPONSE._serialized_start=137
  _FACERECOGNITIONRESPONSE._serialized_end=200
  _EMPTY._serialized_start=202
  _EMPTY._serialized_end=209
  _RECOGNITIONS._serialized_start=212
  _RECOGNITIONS._serialized_end=500
# @@protoc_insertion_point(module_scope)
