# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import faceRecognition_pb2 as faceRecognition__pb2


class RecognitionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recognise = channel.unary_unary(
                '/Recognitions/recognise',
                request_serializer=faceRecognition__pb2.recognitionInit.SerializeToString,
                response_deserializer=faceRecognition__pb2.Empty.FromString,
                )
        self.processImage = channel.unary_unary(
                '/Recognitions/processImage',
                request_serializer=faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
                response_deserializer=faceRecognition__pb2.FaceRecognitionResponse.FromString,
                )
        self.getFaceID1 = channel.unary_unary(
                '/Recognitions/getFaceID1',
                request_serializer=faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
                response_deserializer=faceRecognition__pb2.FaceIDResponse.FromString,
                )
        self.getFaceID2 = channel.unary_unary(
                '/Recognitions/getFaceID2',
                request_serializer=faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
                response_deserializer=faceRecognition__pb2.FaceIDResponse.FromString,
                )
        self.getFaceID3 = channel.unary_unary(
                '/Recognitions/getFaceID3',
                request_serializer=faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
                response_deserializer=faceRecognition__pb2.FaceIDResponse.FromString,
                )


class RecognitionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def recognise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFaceID1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFaceID2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFaceID3(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognitionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recognise': grpc.unary_unary_rpc_method_handler(
                    servicer.recognise,
                    request_deserializer=faceRecognition__pb2.recognitionInit.FromString,
                    response_serializer=faceRecognition__pb2.Empty.SerializeToString,
            ),
            'processImage': grpc.unary_unary_rpc_method_handler(
                    servicer.processImage,
                    request_deserializer=faceRecognition__pb2.FaceRecognitionProcess.FromString,
                    response_serializer=faceRecognition__pb2.FaceRecognitionResponse.SerializeToString,
            ),
            'getFaceID1': grpc.unary_unary_rpc_method_handler(
                    servicer.getFaceID1,
                    request_deserializer=faceRecognition__pb2.FaceRecognitionProcess.FromString,
                    response_serializer=faceRecognition__pb2.FaceIDResponse.SerializeToString,
            ),
            'getFaceID2': grpc.unary_unary_rpc_method_handler(
                    servicer.getFaceID2,
                    request_deserializer=faceRecognition__pb2.FaceRecognitionProcess.FromString,
                    response_serializer=faceRecognition__pb2.FaceIDResponse.SerializeToString,
            ),
            'getFaceID3': grpc.unary_unary_rpc_method_handler(
                    servicer.getFaceID3,
                    request_deserializer=faceRecognition__pb2.FaceRecognitionProcess.FromString,
                    response_serializer=faceRecognition__pb2.FaceIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Recognitions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recognitions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def recognise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognitions/recognise',
            faceRecognition__pb2.recognitionInit.SerializeToString,
            faceRecognition__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def processImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognitions/processImage',
            faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
            faceRecognition__pb2.FaceRecognitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFaceID1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognitions/getFaceID1',
            faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
            faceRecognition__pb2.FaceIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFaceID2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognitions/getFaceID2',
            faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
            faceRecognition__pb2.FaceIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFaceID3(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognitions/getFaceID3',
            faceRecognition__pb2.FaceRecognitionProcess.SerializeToString,
            faceRecognition__pb2.FaceIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
